"""drop_task_scheduled_start

Revision ID: 0eaa42248f38
Revises: 893574a03e76
Create Date: 2026-06-23 17:31:50.623167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0eaa42248f38'
down_revision: Union[str, None] = '893574a03e76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('scheduled_start')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_start', sa.DATE(), nullable=True))

    # ### end Alembic commands ###
