"""task parent_task_id

Revision ID: f83c22ab757c
Revises: 61ed365bec4c
Create Date: 2026-06-02 21:04:36.163313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f83c22ab757c'
down_revision: Union[str, None] = '61ed365bec4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_task_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_tasks_parent_task_id', 'tasks', ['parent_task_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_parent_task_id', type_='foreignkey')
        batch_op.drop_column('parent_task_id')

    # ### end Alembic commands ###
