"""task_dependencies table

Revision ID: 3263531ae531
Revises: d036d1c48a82
Create Date: 2026-06-02 22:09:38.857196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3263531ae531'
down_revision: Union[str, None] = 'd036d1c48a82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('depends_on_task_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_dependencies', schema=None) as batch_op:
        batch_op.create_index('uq_task_dependencies_active_edge', ['task_id', 'depends_on_task_id'], unique=True, sqlite_where=sa.text('deleted_at IS NULL'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_dependencies', schema=None) as batch_op:
        batch_op.drop_index('uq_task_dependencies_active_edge', sqlite_where=sa.text('deleted_at IS NULL'))

    op.drop_table('task_dependencies')
    # ### end Alembic commands ###
