"""task scheduled_start

Revision ID: 893574a03e76
Revises: 5b5f79d37b6e
Create Date: 2026-06-21 20:04:57.846447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '893574a03e76'
down_revision: Union[str, None] = '5b5f79d37b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_start', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('scheduled_start')

    # ### end Alembic commands ###
