"""inbox reviewed_at

Revision ID: def4d6c65e01
Revises: f186f98aa80e
Create Date: 2026-05-31 13:49:09.412762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'def4d6c65e01'
down_revision: Union[str, None] = 'f186f98aa80e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbox_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbox_items', schema=None) as batch_op:
        batch_op.drop_column('reviewed_at')

    # ### end Alembic commands ###
