"""inbox matched_alias

Revision ID: edb902c152de
Revises: 55c3b04ca17b
Create Date: 2026-07-03 14:00:13.846644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'edb902c152de'
down_revision: Union[str, None] = '55c3b04ca17b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbox_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matched_alias', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbox_items', schema=None) as batch_op:
        batch_op.drop_column('matched_alias')

    # ### end Alembic commands ###
