"""task estimated_minutes

Revision ID: d036d1c48a82
Revises: f83c22ab757c
Create Date: 2026-06-02 21:26:57.200203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd036d1c48a82'
down_revision: Union[str, None] = 'f83c22ab757c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_minutes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('estimated_minutes')

    # ### end Alembic commands ###
