"""inbox, training examples, candidate tasks

Revision ID: f186f98aa80e
Revises: e9ef4d8a1205
Create Date: 2026-05-31 10:01:36.732238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f186f98aa80e'
down_revision: Union[str, None] = 'e9ef4d8a1205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_training_examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('input_text', sa.String(), nullable=False),
    sa.Column('model_output_json', sa.String(), nullable=False),
    sa.Column('corrected_output_json', sa.String(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('model_profile', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inbox_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.String(), nullable=False),
    sa.Column('input_hash', sa.String(), nullable=False),
    sa.Column('source', sa.Enum('web', 'discord', name='inboxsource'), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('project_hint', sa.String(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('model_output_json', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inbox_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inbox_items_input_hash'), ['input_hash'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inbox_item_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('assignee_hint', sa.String(), nullable=True))
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(
            'fk_tasks_inbox_item_id', 'inbox_items', ['inbox_item_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_inbox_item_id', type_='foreignkey')
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('assignee_hint')
        batch_op.drop_column('confidence')
        batch_op.drop_column('inbox_item_id')

    with op.batch_alter_table('inbox_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inbox_items_input_hash'))

    op.drop_table('inbox_items')
    op.drop_table('ai_training_examples')
    # ### end Alembic commands ###
