"""project aliases + inbox match suggestion

Revision ID: fb22c3d11646
Revises: def4d6c65e01
Create Date: 2026-05-31 16:01:48.914949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fb22c3d11646'
down_revision: Union[str, None] = 'def4d6c65e01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inbox_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suggested_project_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('match_input_text', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('match_output_json', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('match_model_name', sa.String(), nullable=True))
        batch_op.create_foreign_key(
            'fk_inbox_items_suggested_project_id', 'projects', ['suggested_project_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbox_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inbox_items_suggested_project_id', type_='foreignkey')
        batch_op.drop_column('match_model_name')
        batch_op.drop_column('match_output_json')
        batch_op.drop_column('match_input_text')
        batch_op.drop_column('suggested_project_id')

    op.drop_table('project_aliases')
    # ### end Alembic commands ###
