"""task deleted_with_project_id

Revision ID: 5be1ff02ca06
Revises: 0eaa42248f38
Create Date: 2026-06-24 21:17:12.714245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5be1ff02ca06'
down_revision: Union[str, None] = '0eaa42248f38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_with_project_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_tasks_deleted_with_project_id_projects',
            'projects',
            ['deleted_with_project_id'],
            ['id'],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_tasks_deleted_with_project_id_projects', type_='foreignkey'
        )
        batch_op.drop_column('deleted_with_project_id')

    # ### end Alembic commands ###
