"""task breakdown_output_json

Revision ID: 5b5f79d37b6e
Revises: b9f8eaebb17c
Create Date: 2026-06-21 12:05:25.250580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5b5f79d37b6e'
down_revision: Union[str, None] = 'b9f8eaebb17c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('breakdown_output_json', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('breakdown_output_json')

    # ### end Alembic commands ###
