"""task deleted_with_task_id

Marks tasks cascade-soft-deleted because an ancestor task was trashed, so one
trash_task can be undone as a unit (BUG #192) without sweeping in subtasks that
were already in the trash. Plain Integer, no FK: purges destroy rows and a
stale marker must stay inert rather than block or cascade. Rows trashed before
this migration keep NULL and stay root-only restores.

Revision ID: 93c179708075
Revises: 9f2ce6b4d1a7
Create Date: 2026-07-25 21:25:05.249099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '93c179708075'
down_revision: Union[str, None] = '9f2ce6b4d1a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_with_task_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('deleted_with_task_id')

    # ### end Alembic commands ###
