"""task deferred_until

Revision ID: 55c3b04ca17b
Revises: 7ebcc24824c9
Create Date: 2026-07-03 08:25:09.830482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '55c3b04ca17b'
down_revision: Union[str, None] = '7ebcc24824c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deferred_until', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('deferred_until')

    # ### end Alembic commands ###
