"""add recurrence fields

Revision ID: b9f8eaebb17c
Revises: 9b2c1d7e4a6f
Create Date: 2026-06-20 22:26:28.184900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b9f8eaebb17c'
down_revision: Union[str, None] = '9b2c1d7e4a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repeat_interval', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('recurrence_id', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('recurrence_id')
        batch_op.drop_column('repeat_interval')

    # ### end Alembic commands ###
