#!/usr/bin/env bash
# Regenerate design-kit/app.css: the src/styles partials flattened in the
# exact order the index.css barrel imports them (what Vite inlines).
# Run from the repo root after any stylesheet change; see design-kit/README.md.
set -euo pipefail
cd "$(dirname "$0")/.."

barrel=frontend/src/index.css
out=design-kit/app.css

{
  echo "/* GENERATED by scripts/refresh_design_kit.sh — do not hand-edit."
  echo "   Flattened from frontend/src/styles/* in $barrel import order. */"
  grep -oE "@import '\./styles/[^']+';" "$barrel" | sed "s|@import '\./\(.*\)';|\1|" |
    while read -r partial; do
      printf '\n/* ==== %s ==== */\n' "$partial"
      cat "frontend/src/$partial"
    done
} > "$out"

echo "wrote $out ($(wc -l < "$out") lines)"
